query GetCrossChainTasks($first: Int!, $chainNames: [String!]!) {
  crossChainTasks(first: $first, chainNames: $chainNames) {
    chainName
    taskID
    lang
    disputed
    requester
    deadline
  }
}
